services:
  app:
    build:

      context: .
      dockerfile: Dockerfile

    container_name: referrals-app

    restart: unless-stopped

    ports:
      - "8081:80"

    env_file:
      - .env

  db:
    image: mariadb:10.6

    restart: unless-stopped

    environment:

      MYSQL_DATABASE: referrals
      MYSQL_USER: referrals
      MYSQL_PASSWORD: referrals

      MYSQL_ROOT_PASSWORD: ${ MYSQL_ROOT_PASSWORD }

    volumes:
      - mariadb_data:/var/lib/mysql


volumes:
  mariadb_data: